# -*- coding: utf-8 -*-
"""Zomato Data Analyst Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3gqjeqySf8s3ahylop1k8NuQJPJNZz3

Step 1: Data Ingestion
"""

import pandas as pd

df = pd.read_csv("zomato.csv", encoding='latin1')
print(df.head())

"""Step 2: Data Cleaning"""

df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

df['Average Cost for two'] = df['Average Cost for two'].astype(int)
df['Aggregate rating'] = df['Aggregate rating'].astype(float)

df = df[df['Rating text'] != 'NEW']
df = df[df['Rating text'] != '-']

"""Step 3: Feature Engineering"""

df['Cost_per_person'] = df['Average Cost for two'] / 2

df['Online Delivery'] = df['Has Online delivery'].map({'Yes':1, 'No':0})
df['Table booking'] = df['Has Table booking'].map({'Yes':1, 'No':0})

"""Step 4: Store in SQL"""

import sqlite3

conn = sqlite3.connect("zomato.db")
df.to_sql("restaurants", conn, if_exists="replace", index=False)

"""Step 5: Data Analysis (Business Insights)"""

df['City'].value_counts().head(10)

"""Best Restaurant"""

df.sort_values(by='Aggregate rating', ascending=False).head(10)

"""Cost vs Rating"""

df[['Cost_per_person', 'Aggregate rating']].corr()

"""Step 6: Visualization"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Online Delivery', data=df)
plt.show()